import type { Folder, Node, Root } from "fumadocs-core/page-tree";
import { createElement } from "react";
import addedManifest from "./generated/component-added.json";
import type { source } from "./source";

const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * Slug → the date the doc first appeared in git, generated by
 * `pnpm calculate-new`. This is what makes the badge automatic: nothing has to
 * be written in frontmatter for a new component to be marked.
 */
const ADDED_DATES = addedManifest.added as Record<string, string>;

function isNew(date: Date): boolean {
  return Date.now() - date.getTime() < SEVEN_DAYS_MS;
}

/**
 * An explicit `new:` in frontmatter always wins, so a component can be badged
 * for a relaunch or held back on purpose. Otherwise the git add date decides.
 */
function resolveAddedDate(frontmatterDate: unknown, slug: string): Date | null {
  if (frontmatterDate instanceof Date) {
    return frontmatterDate;
  }

  const generated = ADDED_DATES[slug];
  if (!generated) {
    return null;
  }

  const parsed = new Date(generated);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

function NewBadge() {
  return createElement(
    "span",
    {
      className:
        "ml-auto inline-flex shrink-0 items-center rounded-full bg-primary px-1.5 py-0.5 font-medium text-[10px] text-primary-foreground leading-none",
    },
    "New"
  );
}

function decorateNode(node: Node, newUrls: Set<string>): Node {
  if (node.type === "page" && newUrls.has(node.url)) {
    return {
      ...node,
      // The key belongs on this outer element, not on the two children: fumadocs
      // renders a sidebar item's `name` inside a list alongside its icon, so the
      // node we hand back is itself a list child and React wants it keyed.
      name: createElement(
        "span",
        {
          className: "flex w-full items-center gap-1",
          key: `${node.url}-name`,
        },
        node.name,
        createElement(NewBadge, { key: "badge" })
      ),
    };
  }

  if (node.type === "folder" && node.children) {
    return {
      ...node,
      children: node.children.map((child: Node) =>
        decorateNode(child, newUrls)
      ),
    } as Folder;
  }

  return node;
}

export function decorateNewPages(tree: Root, src: typeof source): Root {
  const newUrls = new Set<string>();

  for (const page of src.getPages()) {
    const data = page.data as { new?: Date };
    const added = resolveAddedDate(data.new, page.slugs.join("/"));
    if (added && isNew(added)) {
      newUrls.add(page.url);
    }
  }

  if (newUrls.size === 0) {
    return tree;
  }

  return {
    ...tree,
    children: tree.children.map((child: Node) => decorateNode(child, newUrls)),
  };
}
