import {
  IconAbcLettersFill24,
  IconAccessibilityFill24,
  IconAiFill24,
  IconAlbumFill24,
  IconArrowRotateClockwiseFill24,
  IconAtomFill24,
  IconBag24Fill24,
  IconBellFill24,
  IconBinaryFill24,
  IconBlockquoteFill24,
  IconBoltFill24,
  IconBookBookmarkFill24,
  IconBooleanIntersectFill24,
  IconBooleanUnionFill24,
  IconBox3Fill24,
  IconBrainFill24,
  IconBulletListFill24,
  IconCalendarFill24,
  IconCardsFill24,
  IconCaretMaximizeFill24,
  IconCarousel2Fill24,
  IconChartBarTrendUpFill24,
  IconChartPieFill24,
  IconChatBubblePlusFill24,
  IconCheckboxChecked2Fill24,
  IconChevronDownFill24,
  IconCircleDashedFill24,
  IconCircleMediaPlayFill24,
  IconCircleQuestionFill24,
  IconCircularLoaderFill24,
  IconClock2Fill24,
  IconClockFill24,
  IconCloudFill24,
  IconCodeEditorFill24,
  IconCodeFill24,
  IconCompareItemsFill24,
  IconCompass2Fill24,
  IconContrastFill24,
  IconCopyFill24,
  IconCropFill24,
  IconCursor2Fill24,
  IconDotsLoaderFill24,
  IconDownloadFill24,
  IconDropletFill24,
  IconExpandFill24,
  IconEyeScannerFill24,
  IconFaceSmileFill24,
  IconFileFill24,
  IconFileTreeFill24,
  IconFolderOpenFill24,
  IconFrameEffectFill24,
  IconFrameFill24,
  IconGamepad2Fill24,
  IconGauge2Fill24,
  IconGlobe2Fill24,
  IconGrid3Fill24,
  IconGridLayout10Fill24,
  IconHashtagFill24,
  IconHeartFill24,
  IconImageFill24,
  IconImagePlusFill24,
  IconImagesFill24,
  IconKeyFill24,
  IconLayersFill24,
  IconLayersStackedFill24,
  IconLayoutBottomFill24,
  IconLayoutTopFill24,
  IconLetterAFill24,
  IconLibraryCabinetFill24,
  IconLightbulbFill24,
  IconListCheckbox2Fill24,
  IconListCheckFill24,
  IconMagicWandSparkleFill24,
  IconMagnetFill24,
  IconMagnifierFill24,
  IconMessage2Fill24,
  IconMessageFill24,
  IconMessagesFill24,
  IconMonitorFill24,
  IconMusicPlayFill24,
  IconPaintbrush2Fill24,
  IconPaintbrushFill24,
  IconPaletteFill24,
  IconPeople3Fill24,
  IconPin2Fill24,
  IconPopcornFill24,
  IconPowerLevelFill24,
  IconQuoteFill24,
  IconRainbowFill24,
  IconRectLoginFill24,
  IconRefresh2Fill24,
  IconRocketFill24,
  IconRulerFill24,
  IconScissorsFill24,
  IconShapeAdjustFill24,
  IconShapesFill24,
  IconShareLeft3Fill24,
  IconShieldCheckFill24,
  IconSidebarRightFill24,
  IconSliders2Fill24,
  IconSparkleFill24,
  IconStampFill24,
  IconStarFill24,
  IconSunFill24,
  IconSwapNodesFill24,
  IconTagFill24,
  IconTextColumnsFill24,
  IconToggleFill24,
  IconTriangleWarningFill24,
  IconTrophyFill24,
  IconUploadFill24,
  IconUser2Fill24,
  IconUserFill24,
  IconVectorFill24,
  IconWalletFill24,
  IconWaveformLinesFill24,
  IconWindowCodeFill24,
  IconWindowCurtainsFill24,
  IconWindowDevFill24,
  IconWindowFill24,
  IconWrenchFill24,
} from "nucleo-core-fill-24";
import { createElement } from "react";

type NucleoIcon = React.ComponentType<{ className?: string; size?: number }>;

const LUCIDE_TO_NUCLEO: Record<string, NucleoIcon> = {
  Accessibility: IconAccessibilityFill24,
  Album: IconAlbumFill24,
  Aperture: IconFrameEffectFill24,
  AppWindow: IconWindowFill24,
  ArrowLeftRight: IconSwapNodesFill24,
  ArrowRightLeft: IconSwapNodesFill24,
  BadgeDollarSign: IconBoltFill24,
  BarChart2: IconChartBarTrendUpFill24,
  Bell: IconBellFill24,
  Binary: IconBinaryFill24,

  // Shader and SDF transitions — blank in the sidebar since they were added.
  Blend: IconBooleanIntersectFill24,
  Blinds: IconWindowCurtainsFill24,
  BookOpen: IconBookBookmarkFill24,
  Bot: IconAiFill24,
  Box: IconBox3Fill24,
  Brain: IconBrainFill24,
  Briefcase: IconBag24Fill24,
  Calendar: IconCalendarFill24,
  Cards: IconCardsFill24,
  CaseSensitive: IconAbcLettersFill24,
  ChartPie: IconChartPieFill24,
  ChevronDown: IconChevronDownFill24,
  Circle: IconCircleDashedFill24,
  CircleDot: IconDotsLoaderFill24,
  Clock: IconClockFill24,
  Cloud: IconCloudFill24,
  Code: IconCodeFill24,
  Code2: IconCodeEditorFill24,
  Columns3: IconTextColumnsFill24,
  Copy: IconCopyFill24,
  Crop: IconCropFill24,
  Disc3: IconMusicPlayFill24,
  Download: IconDownloadFill24,
  Droplet: IconDropletFill24,
  Droplets: IconDropletFill24,

  // AI section. Anything not listed here renders no icon at all, which is how
  // half the AI pages ended up with a blank slot in the sidebar.
  FileDiff: IconCompareItemsFill24,
  FileText: IconFileFill24,
  FolderOpen: IconFolderOpenFill24,
  FolderTree: IconFileTreeFill24,
  Frame: IconFrameFill24,
  GalleryHorizontal: IconCarousel2Fill24,
  GalleryHorizontalEnd: IconImagesFill24,
  Gamepad2: IconGamepad2Fill24,
  Gauge: IconGauge2Fill24,
  Globe: IconGlobe2Fill24,
  Grid3x3: IconGrid3Fill24,
  Hash: IconHashtagFill24,
  Heart: IconHeartFill24,
  HelpCircle: IconCircleQuestionFill24,
  History: IconClock2Fill24,
  Image: IconImageFill24,
  ImagePlus: IconImagePlusFill24,
  Images: IconImagesFill24,
  KeyRound: IconKeyFill24,
  Layers: IconLayersFill24,
  Layers3: IconLayersStackedFill24,
  LayoutDashboard: IconGridLayout10Fill24,
  LayoutGrid: IconGridLayout10Fill24,
  Library: IconLibraryCabinetFill24,
  Lightbulb: IconLightbulbFill24,
  List: IconBulletListFill24,
  ListChecks: IconListCheckbox2Fill24,
  ListOrdered: IconListCheckFill24,
  Loader: IconDotsLoaderFill24,
  LoaderCircle: IconCircularLoaderFill24,
  LogIn: IconRectLoginFill24,
  Magnet: IconMagnetFill24,
  Merge: IconBooleanUnionFill24,
  MessageCircle: IconMessageFill24,
  MessageSquare: IconMessage2Fill24,
  MessageSquarePlus: IconChatBubblePlusFill24,
  MessageSquareQuote: IconBlockquoteFill24,
  MessagesSquare: IconMessagesFill24,
  MonitorPlay: IconMonitorFill24,
  MousePointer: IconCursor2Fill24,
  MousePointerClick: IconCursor2Fill24,
  MoveHorizontal: IconExpandFill24,
  Navigation: IconCompass2Fill24,
  Orbit: IconAtomFill24,
  Paintbrush: IconPaintbrushFill24,
  Paintbrush2: IconPaintbrush2Fill24,
  Palette: IconPaletteFill24,
  PanelBottom: IconLayoutBottomFill24,
  PanelLeft: IconSidebarRightFill24,
  PanelsTopLeft: IconWindowCodeFill24,
  PanelTopOpen: IconLayoutTopFill24,
  PenTool: IconVectorFill24,
  Pin: IconPin2Fill24,
  PlayCircle: IconCircleMediaPlayFill24,
  Popcorn: IconPopcornFill24,
  Power: IconPowerLevelFill24,
  Quote: IconQuoteFill24,
  Rainbow: IconRainbowFill24,
  RectangleEllipsis: IconDotsLoaderFill24,
  RefreshCw: IconRefresh2Fill24,
  Rocket: IconRocketFill24,
  RotateCw: IconArrowRotateClockwiseFill24,
  Ruler: IconRulerFill24,
  ScanFace: IconEyeScannerFill24,
  Scissors: IconScissorsFill24,
  Search: IconMagnifierFill24,
  Shapes: IconShapesFill24,
  Share2: IconShareLeft3Fill24,
  ShieldCheck: IconShieldCheckFill24,
  ShoppingCart: IconBag24Fill24,
  SlidersHorizontal: IconSliders2Fill24,
  Smile: IconFaceSmileFill24,
  SmilePlus: IconFaceSmileFill24,
  Sparkles: IconSparkleFill24,
  Square: IconExpandFill24,
  SquareCheck: IconCheckboxChecked2Fill24,
  SquareDashedBottom: IconCaretMaximizeFill24,
  SquareStack: IconLayersFill24,
  SquareTerminal: IconWindowDevFill24,
  Squircle: IconShapeAdjustFill24,
  Stamp: IconStampFill24,
  Star: IconStarFill24,
  SunMedium: IconSunFill24,
  SunMoon: IconContrastFill24,
  Tag: IconTagFill24,
  TextSearch: IconMagnifierFill24,
  ToggleLeft: IconToggleFill24,
  Triangle: IconTriangleWarningFill24,
  Trophy: IconTrophyFill24,
  Type: IconLetterAFill24,
  Upload: IconUploadFill24,
  User: IconUserFill24,
  UserRound: IconUser2Fill24,
  Users: IconPeople3Fill24,
  Wallet: IconWalletFill24,
  Wand2: IconMagicWandSparkleFill24,
  Waves: IconWaveformLinesFill24,
  Wrench: IconWrenchFill24,
  Zap: IconBoltFill24,
};

function resolveIcon(name: string | undefined): React.ReactElement | undefined {
  if (!name) {
    return;
  }
  const Icon = LUCIDE_TO_NUCLEO[name];
  if (!Icon) {
    console.warn(`[nucleo-icons-plugin] Unknown icon: ${name}`);
    return;
  }
  return createElement(Icon, { className: "size-4" });
}

function replaceIcon(node: Record<string, unknown>): Record<string, unknown> {
  if (node.icon === undefined || typeof node.icon === "string") {
    node.icon = resolveIcon(node.icon as string | undefined);
  }
  return node;
}

export function nucleoIconsPlugin() {
  return {
    name: "smoothui:nucleo-icons",
    transformPageTree: {
      file: replaceIcon,
      folder: replaceIcon,
      separator: replaceIcon,
    },
  } as unknown as import("fumadocs-core/source").LoaderPlugin;
}
