// Regenerates lib/generated/counts.ts — the single source of truth for "how
// many components/blocks/templates do we have", used by marketing copy, site
// metadata, JSON-LD and the docs.
//
// Why generated rather than computed at runtime: the counts are needed in client
// components (the landing hero, the FAQs), in `generateMetadata`, and inside MDX
// frontmatter, which is parsed before any React runs. A plain module of numbers
// is importable from all three; a function that reads the filesystem is not.
//
// Run with `--check` to fail instead of writing, which is what CI does — the
// generated file is committed, so a drifted count is caught the same way a stale
// lockfile is.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const DOCS_ROOT = join(process.cwd(), "content", "docs");
const OUTPUT_PATH = join(process.cwd(), "lib", "generated", "counts.ts");

// Same definition the blocks index uses: one <Preview> is one block.
const PREVIEW_TAG = /<Preview\s+path="([^"]+)"/g;

/** Doc pages in a section, ignoring its index. One page, one documented item. */
const countPages = async (section: string): Promise<number> => {
  const files = await readdir(join(DOCS_ROOT, section));

  return files.filter((file) => file.endsWith(".mdx") && file !== "index.mdx")
    .length;
};

/**
 * Blocks, counted the way `getBlockCategories` counts them.
 *
 * A block category page documents several blocks, so the page count is the
 * category count and the <Preview> count is the block count. Keeping both in
 * step with the index matters: the landing page and the gallery must not
 * disagree about how many blocks exist.
 */
const countBlocks = async (): Promise<{
  blockCategories: number;
  blocks: number;
}> => {
  const blocksDir = join(DOCS_ROOT, "blocks");
  const files = await readdir(blocksDir);
  let blocks = 0;
  let blockCategories = 0;

  for (const file of files) {
    if (!file.endsWith(".mdx") || file === "index.mdx") {
      continue;
    }

    const body = await readFile(join(blocksDir, file), "utf-8");
    const previews = [...body.matchAll(PREVIEW_TAG)].length;

    if (previews > 0) {
      blocks += previews;
      blockCategories += 1;
    }
  }

  return { blockCategories, blocks };
};

const [components, templates, { blockCategories, blocks }] = await Promise.all([
  countPages("components"),
  countPages("templates"),
  countBlocks(),
]);

if (components === 0 || blocks === 0) {
  console.error(
    `Refusing to write suspicious counts (components: ${components}, blocks: ${blocks}). Is the working directory apps/docs?`
  );
  process.exit(1);
}

const contents = `// GENERATED by scripts/generate-counts.mts — do not edit by hand.
// Run \`pnpm counts\` in apps/docs after adding a component, block or template.

/** Documented components, one per page under /docs/components. */
export const COMPONENT_COUNT = ${components};

/** Individual blocks — every <Preview> across the block category pages. */
export const BLOCK_COUNT = ${blocks};

/** Block categories: pricing, headers, footers, … */
export const BLOCK_CATEGORY_COUNT = ${blockCategories};

/** Full templates, one per page under /docs/templates. */
export const TEMPLATE_COUNT = ${templates};
`;

if (process.argv.includes("--check")) {
  const existing = await readFile(OUTPUT_PATH, "utf-8").catch(() => "");

  if (existing !== contents) {
    console.error(
      `lib/generated/counts.ts is out of date (components: ${components}, blocks: ${blocks}, block categories: ${blockCategories}, templates: ${templates}). Run \`pnpm counts\`.`
    );
    process.exit(1);
  }

  console.log(
    `counts up to date: ${components} components, ${blocks} blocks in ${blockCategories} categories, ${templates} templates`
  );
} else {
  await writeFile(OUTPUT_PATH, contents);
  console.log(
    `wrote lib/generated/counts.ts: ${components} components, ${blocks} blocks in ${blockCategories} categories, ${templates} templates`
  );
}
