import { type ChildProcess, spawn } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium, type Page } from "@playwright/test";
import { galleryComponentSlugs } from "./component-poster-slugs";

const ROOT = join(import.meta.dirname, "..");
const COVERS = join(ROOT, "apps/docs/components/gallery/covers/components");
const MANIFEST = join(ROOT, "apps/docs/components/gallery/component-shots.ts");
const META = join(ROOT, "apps/docs/content/docs/components/meta.json");
const BASE_URL = process.env.DOCS_URL ?? "http://localhost:3000";

/** Capture width. Posters keep this full width so a button is not blown up. */
export const POSTER_VIEWPORT = { height: 1400, width: 560 } as const;

const PAD = 28;
const MAX_HEIGHT = 640;
const MIN_HEIGHT = 112;
const SETTLE_MS = 1200;
const IDENTIFIER_START = /^[A-Za-z_]/;
const CONCURRENCY = 4;

export interface PosterBounds {
  bottom: number;
  top: number;
  viewportHeight: number;
  viewportWidth: number;
}

export interface PosterClip {
  height: number;
  width: number;
  x: number;
  y: number;
}

/**
 * Crop a settled demo to its content, full viewport width, capped so a
 * full-screen shader does not become a multi-thousand-pixel card.
 */
export const posterClip = ({
  bottom,
  top,
  viewportHeight,
  viewportWidth,
}: PosterBounds): PosterClip => {
  const contentTop = Math.min(Math.max(top, 0), viewportHeight);
  const contentBottom = Math.min(Math.max(bottom, 0), viewportHeight);
  let y = Math.max(0, contentTop - PAD);
  let height = contentBottom + PAD - y;

  if (!(height > 0)) {
    return {
      height: Math.min(MIN_HEIGHT, viewportHeight),
      width: viewportWidth,
      x: 0,
      y: 0,
    };
  }

  if (height < MIN_HEIGHT) {
    y = Math.max(0, Math.min(y, viewportHeight - MIN_HEIGHT));
    height = Math.min(MIN_HEIGHT, viewportHeight - y);
  }

  if (height > MAX_HEIGHT) {
    height = MAX_HEIGHT;
  }

  if (y + height > viewportHeight) {
    height = viewportHeight - y;
  }

  return {
    height: Math.max(1, Math.round(height)),
    width: viewportWidth,
    x: 0,
    y: Math.round(y),
  };
};

const wait = (ms: number) =>
  new Promise((resolve) => {
    setTimeout(resolve, ms);
  });

const importName = (slug: string, used: Set<string>): string => {
  const camel = slug.replace(/-([a-z0-9])/g, (_, char: string) =>
    char.toUpperCase()
  );
  const base = IDENTIFIER_START.test(camel) ? camel : `shot${camel}`;
  let name = base;
  let suffix = 2;
  while (used.has(name)) {
    name = `${base}${suffix}`;
    suffix += 1;
  }
  used.add(name);
  return name;
};

const writeManifest = (slugs: readonly string[]) => {
  const present = slugs
    .filter((slug) => existsSync(join(COVERS, `${slug}.webp`)))
    .toSorted((left, right) => left.localeCompare(right));
  const used = new Set<string>();
  const imports = present.map((slug) => {
    const name = importName(slug, used);
    return { name, slug };
  });

  const lines = [
    'import type { StaticImageData } from "next/image";',
    "",
    ...imports.map(
      ({ name, slug }) =>
        `import ${name} from "./covers/components/${slug}.webp";`
    ),
    "",
    "/**",
    " * Posters for the component index. Generated by `pnpm capture:posters`.",
    " * A slug with no file fails `scripts/component-posters.test.ts`.",
    " */",
    "export const COMPONENT_SHOTS: Record<string, StaticImageData> = {",
    ...imports.map(({ name, slug }) =>
      name === slug ? `  ${name},` : `  "${slug}": ${name},`
    ),
    "};",
    "",
  ];

  writeFileSync(MANIFEST, lines.join("\n"), "utf8");
};

const readSlugs = (): string[] => {
  const meta = JSON.parse(readFileSync(META, "utf8")) as { pages: string[] };
  return galleryComponentSlugs(meta.pages);
};

const serverIsUp = async (): Promise<boolean> => {
  try {
    const response = await fetch(BASE_URL, {
      signal: AbortSignal.timeout(4000),
    });
    return response.status > 0;
  } catch {
    return false;
  }
};

const startServer = async (): Promise<ChildProcess | undefined> => {
  if (await serverIsUp()) {
    return;
  }

  const child = spawn("pnpm", ["--filter", "docs", "dev"], {
    cwd: ROOT,
    env: {
      ...process.env,
      NEXT_PUBLIC_ENABLE_VERCEL_ANALYTICS: "false",
    },
    stdio: "inherit",
  });

  const deadline = Date.now() + 120_000;
  while (Date.now() < deadline) {
    // biome-ignore lint/performance/noAwaitInLoops: the probe is the wait for the dev server
    const up = await serverIsUp();
    if (up) {
      return child;
    }
    if (child.exitCode !== null) {
      throw new Error("docs dev server exited before it was ready");
    }
    await wait(500);
  }

  child.kill("SIGTERM");
  throw new Error("docs dev server did not start");
};

const MEASURE_BOUNDS = `(() => {
  const root = document.getElementById("poster-root");
  const visible = (element) => {
    let current = element;
    while (current) {
      const style = getComputedStyle(current);
      if (style.display === "none" || style.visibility === "hidden") {
        return false;
      }
      if (Number.parseFloat(style.opacity) === 0) {
        return false;
      }
      current = current.parentElement;
    }
    return true;
  };

  let top = Number.POSITIVE_INFINITY;
  let bottom = Number.NEGATIVE_INFINITY;

  if (root) {
    const nodes = [root, ...root.querySelectorAll("*")];
    for (const node of nodes) {
      if (!visible(node)) {
        continue;
      }
      const rect = node.getBoundingClientRect();
      if (rect.width < 2 || rect.height < 2) {
        continue;
      }
      top = Math.min(top, rect.top);
      bottom = Math.max(bottom, rect.bottom);
    }
  }

  return {
    bottom: Number.isFinite(bottom) ? bottom : 0,
    top: Number.isFinite(top) ? top : 0,
    viewportHeight: window.innerHeight,
    viewportWidth: window.innerWidth,
  };
})()`;

const measure = (page: Page): Promise<PosterBounds> =>
  page.evaluate(MEASURE_BOUNDS);

const captureSlug = async (page: Page, slug: string) => {
  const response = await page.goto(`${BASE_URL}/blocks/preview/${slug}`, {
    timeout: 90_000,
    waitUntil: "domcontentloaded",
  });

  if (response && response.status() >= 400) {
    throw new Error(`${slug} returned ${response.status()}`);
  }

  const rooted = await page
    .waitForSelector("#poster-root", { timeout: 15_000 })
    .then(() => true)
    .catch(() => false);

  if (rooted) {
    await page.evaluate("document.fonts.ready");
    await wait(SETTLE_MS);
  }

  let bounds: PosterBounds = rooted
    ? await measure(page)
    : {
        bottom: 0,
        top: 0,
        viewportHeight: POSTER_VIEWPORT.height,
        viewportWidth: POSTER_VIEWPORT.width,
      };
  if (bounds.bottom - bounds.top < 24) {
    await wait(800);
    bounds = await measure(page);
  }

  let labeled = false;
  if (bounds.bottom - bounds.top < 24) {
    labeled = true;
    console.warn(`  ${slug} rendered nothing; capturing a label`);
    await page.setContent(
      `<!doctype html><html><body style="margin:0;background:#fafafa;color:#171717;font-family:ui-sans-serif,system-ui,sans-serif"><div style="padding:36px 32px;font-size:18px;font-weight:600">${slug}</div></body></html>`
    );
    await page.setViewportSize({
      height: 180,
      width: POSTER_VIEWPORT.width,
    });
    bounds = {
      bottom: 180,
      top: 0,
      viewportHeight: 180,
      viewportWidth: POSTER_VIEWPORT.width,
    };
  }

  const clip = posterClip(bounds);
  const png = join(tmpdir(), `smoothui-poster-${slug}.png`);
  const webp = join(COVERS, `${slug}.webp`);

  try {
    await page.screenshot({
      clip,
      path: png,
      type: "png",
    });

    await new Promise<void>((resolve, reject) => {
      const encoder = spawn("cwebp", ["-q", "78", "-m", "4", png, "-o", webp], {
        stdio: "ignore",
      });
      encoder.on("error", reject);
      encoder.on("exit", (code) => {
        if (code === 0) {
          resolve();
          return;
        }
        reject(new Error(`cwebp exited ${code} for ${slug}`));
      });
    });
  } finally {
    rmSync(png, { force: true });
    if (labeled) {
      await page.setViewportSize(POSTER_VIEWPORT);
    }
  }
};

const parseArgs = (argv: readonly string[]) => {
  const force = argv.includes("--force");
  const onlyIndex = argv.indexOf("--only");
  const only =
    onlyIndex >= 0
      ? (argv[onlyIndex + 1] ?? "")
          .split(",")
          .map((slug) => slug.trim())
          .filter((slug) => slug.length > 0)
      : undefined;

  return { force, only };
};

const main = async () => {
  const { force, only } = parseArgs(process.argv.slice(2));
  const slugs = readSlugs();
  const targets = only ? slugs.filter((slug) => only.includes(slug)) : slugs;

  if (only && targets.length !== only.length) {
    const known = new Set(slugs);
    const unknown = only.filter((slug) => !known.has(slug));
    throw new Error(`Unknown component slug: ${unknown.join(", ")}`);
  }

  mkdirSync(COVERS, { recursive: true });

  const pending = force
    ? targets
    : targets.filter((slug) => !existsSync(join(COVERS, `${slug}.webp`)));

  console.log(
    `${slugs.length} components, ${pending.length} to capture${force ? " (--force)" : ""}.`
  );

  let server: ChildProcess | undefined;
  const stopServer = () => {
    if (server && server.exitCode === null) {
      server.kill("SIGTERM");
    }
  };

  process.on("SIGINT", () => {
    stopServer();
    process.exit(1);
  });

  const failed: string[] = [];

  try {
    if (pending.length > 0) {
      server = await startServer();
      const browser = await chromium.launch({
        args: ["--enable-webgl", "--ignore-gpu-blocklist", "--use-gl=angle"],
      });
      const context = await browser.newContext({
        colorScheme: "light",
        deviceScaleFactor: 2,
        reducedMotion: "no-preference",
        viewport: POSTER_VIEWPORT,
      });

      let cursor = 0;
      const worker = async () => {
        const page = await context.newPage();
        while (cursor < pending.length) {
          const index = cursor;
          cursor += 1;
          const slug = pending[index];
          if (!slug) {
            continue;
          }
          try {
            // biome-ignore lint/performance/noAwaitInLoops: one page captures slugs one after another
            await captureSlug(page, slug);
            console.log(`  ${index + 1}/${pending.length} ${slug}`);
          } catch (error) {
            const message =
              error instanceof Error ? error.message : String(error);
            console.error(`  failed ${slug}: ${message}`);
            rmSync(join(COVERS, `${slug}.webp`), { force: true });
            failed.push(slug);
          }
        }
        await page.close();
      };

      await Promise.all(
        Array.from({ length: Math.min(CONCURRENCY, pending.length) }, () =>
          worker()
        )
      );

      await browser.close();
    }
  } finally {
    writeManifest(slugs);
    stopServer();
  }

  const missing = slugs.filter(
    (slug) => !existsSync(join(COVERS, `${slug}.webp`))
  );

  console.log(`Manifest written to ${MANIFEST}`);

  if (failed.length > 0 || (only === undefined && missing.length > 0)) {
    console.error(
      `Missing posters: ${(failed.length > 0 ? failed : missing).join(", ")}`
    );
    process.exit(1);
  }
};

const isDirectRun = process.argv[1]?.includes("capture-component-posters");

if (isDirectRun) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
